### ISSUE TITLE
Lets make it a deal.

### ISSUE THREAD

**Issue by olivertzeng** [MTACS/LynxLocalizations#43]
You give me that $1.50 for buying Lynx, and I'll translate into a language. Deal?

**Comment by olivertzeng** [comment]
Ok sorry the Lynx tweak looks kinda nice
I'll translate it into my language although I really don't own that tweak rn
will prob buy it though
Sorry for the stupid myself from last year lol

**Comment by MTACS** [comment]
No worries at all, I'll give you a redeem code, I just need your Havoc username. I closed the issue as I'm reworking the localizations completely

**Comment by olivertzeng** [comment]
> No worries at all, I'll give you a redeem code, I just need your Havoc username. I closed the issue as I'm reworking the localizations completely

the havoc username is @olivertzeng Thanks!

I thought that it was kinda rude though because i normally do that for free

**Comment by olivertzeng** [comment]
I'm doing the translations

**Comment by MTACS** [comment]
Gift added to account 👍

**Comment by olivertzeng** [comment]
> Gift added to account 👍

Help when I tried to apply settings in the app it just got stuck. Ive only just enabled the App Store updates tab settings!
And also applying it from settings doesn't work either. @MTACS

**Comment by MTACS** [comment]
By stuck do you mean it keeps respringing? Could you [open an issue](https://github.com/MTACS/Lynx2/issues/new?assignees=MTACS&labels=bug&template=lynx-2-bug-report.md&title=) on the Lynx 2 page

**Comment by olivertzeng** [comment]
> By stuck do you mean it keeps respringing? Could you [open an issue](https://github.com/MTACS/Lynx2/issues/new?assignees=MTACS&labels=bug&template=lynx-2-bug-report.md&title=) on the Lynx 2 page

No, it was just stuck when clicking the apply button
Didn't even respring

**Comment by olivertzeng** [comment]
https://github.com/MTACS/Lynx2/issues/284
@MTACS Done reporting
